project:
  type: website
  output-dir: docs

# Meta
description-meta: "Course on Agribusiness Entrepreneurship developed by Dr. Lauren Chenarides, exploring entrepreneurial thinking, business models, and market challenges in the food and agriculture sector."
author-meta: "Lauren Chenarides"

website:
  title: "Ag Entrepreneurship"
  description: "Course on Agribusiness Entrepreneurship developed by Dr. Lauren Chenarides."
  navbar:
    background: light
    left:
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Schedule"
        href: 2025/schedule.qmd
      - text: "Semester Checklist"
        href: 2025/project-timeline.qmd
      - text: "Weekly Case Studies"
        menu:                           
        - text: "Case Study Coursepack"
          href: cases/coursepack.qmd
        - text: "Case Study Assignments & Signups"
          href: cases/case-assignment.qmd
        - text: "Case Study Role Descriptions"
          href: cases/case-roles.qmd
        - text: "How We Use Case Studies"
          href: cases/case-method.qmd 
      - text: "Podcast Project"
        href: podcast/podcast-instructions.qmd                
      - text: "Case Competition"
        href: cases/case-competition.qmd                
      - text: "Your E-IDP"
        href: mentors/eidp.qmd
      - text: "Mentors"
        menu:                           
        - text: "Meet the 2025 Cohort"
          href: mentors/mentors.qmd
        - text: "Mentor Guide & Timeline"
          href: mentors/mentor-instructions.qmd
      - text: "Resources"
        menu:                           
        - text: "Fishbowl Discussion Guide"
          href: cases/templates/fishbowl_discussion_guide.Rmd
        - text: "Observer Feedback Form"
          href: cases/templates/observer-form.qmd
        - text: "Entrepreneurial Characteristics Handout"
          href: mentors/characteristics_handout.Rmd
      # - text: Archive
      #   menu:
      #     - text: Fall 2025
      #       href: 2025/schedule.qmd         
      # - text: Dr. Lauren Chenarides
      #   href: https://scholar.google.com/citations?user=07RAgEQAAAAJ&hl=en
      #   target: _blank        
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-224
  page-navigation: true
  page-footer: 
    left: "[Lauren Chenarides](https://github.com/laurenchenarides/csu-arec-224) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-224
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/laurenchenarides/csu-arec-224
  repo-actions: [edit, issue, source]
  open-graph: true
  site-url: "https://github.com/laurenchenarides/csu-arec-224"
  google-analytics:
    tracking-id: "G-GG4GM3TPXK"
    anonymize-ip: true

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true

execute: 
  freeze: auto

comments:
  hypothesis: false
  

