project:
  type: website
  output-dir: docs

# Meta
description-meta: "Course on Agribusiness Entrepreneurship developed by Dr. Lauren Chenarides, exploring entrepreneurial thinking, business models, and market challenges in the food and agriculture sector."
author-meta: "Lauren Chenarides"

website:
  title: "Ag Entrepreneurship"
  description: "Course on Agribusiness Entrepreneurship developed by Dr. Lauren Chenarides."
  navbar:
    background: light
    left:
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: 2025/schedule.qmd
      - text: Lectures
        href: lectures.qmd
      - text: Case Studies
        menu:                           
        - text: Access Coursepack
          href: coursepack.qmd
        - text: The Case Method
          href: casemethod.qmd 
      - text: Mentors
        href: http://drganghe.github.io/climate-guest-speakers
        target: _blank
      - text: Case Competition
        href: competition.qmd                
      # - text: Archive
      #   menu:
      #     - text: Fall 2025
      #       href: 2025/schedule.qmd         
      - text: Dr. Lauren Chenarides
        href: https://scholar.google.com/citations?user=07RAgEQAAAAJ&hl=en
        target: _blank        
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-224
  page-navigation: true
  page-footer: 
    left: "[Lauren Chenarides](https://github.com/laurenchenarides/csu-arec-224) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-224
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/laurenchenarides/csu-arec-224
  repo-actions: [edit, issue, source]
  open-graph: true
  site-url: "https://github.com/laurenchenarides/csu-arec-224"
  google-analytics:
    tracking-id: "G-GG4GM3TPXK"
    anonymize-ip: true

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true

execute: 
  freeze: auto

comments:
  hypothesis: false
  

