### Undocumented Student Support

Any CSU student who faces challenges or hardships due to their legal status in the United States and believes that it may impact their academic performance in this course is encouraged to visit  [Student Support Services for Undocumented, DACA & ASSET](https://undocumented.colostate.edu/) for resources and support. Additionally, only if you feel comfortable, please notify your professor so they may pass along any additional resources they may possess. 

### Food Insecurity

Any CSU student (along with faculty and staff) who is experiencing food insecurity can receive support from the [Rams Against Hunger](https://lsc.colostate.edu/slice/slice-engagement/rams-against-hunger/) program. Services include a food pantry, a meal-swipe program, pocket pantries, and in-person assistance with navigating federal aid eligibility. The RAH page includes numerous resources as well as county, state and federal programs which are described and linked.

### Title IX/Interpersonal Violence 

For the full statement regarding role and responsibilities about reporting harassment, sexual harassment, sexual misconduct, domestic violence, dating violence, stalking, and the retaliation policy please go to: [Title IX – Sexual Assault, Sexual Violence, Sexual Harassment](http://oeo.colostate.edu/title-ix-sexual-assault). 

If you feel that your rights have been compromised at CSU, several resources are available to assist: 

- Student Resolution Center, 200 Lory Student Center, 491-7165 
- Office of Equal Opportunity, 101 Student Services, 491-5836

A note about interpersonal violence: If you or someone you know has experienced sexual assault, relationship violence and/or stalking, know that you are not alone. As instructors, we are required by law to notify university officials about disclosures related to interpersonal violence. Confidential victim advocates are available 24 hours a day, 365 days a year to provide support related to the emotional, physical, physiological and legal aftermath of interpersonal violence. Contact the Victim Assistance Team at: 970-492-4242.

## Diversity and Inclusion

In an ideal world, science would be objective. However, much of science is subjective and is historically built on a small subset of privileged voices. I acknowledge that many of the readings for this course were authored by white men. Furthermore, the course often focuses on economic principles, policies, and concepts that were mostly developed by white men. I have made recent edits to the materials to try to reflect a more diverse perspective. However, I acknowledge that it is possible that there may be both overt and covert biases in the material due to the lens with which it was written, even though the material is primarily of a scientific nature. Integrating a diverse set of experiences is important for a more comprehensive understanding of science. Please contact me (in person or via Canvas) or submit anonymous feedback if you have any suggestions to improve the quality of the course materials (I have a paper mailbox on the second floor of Nutrien if you are worried about leaving an electronic trace). I would like to create a learning environment for my students that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) To help accomplish this:

- If you have a name and/or set of pronouns that differ from those that appear in your official CSU records, please let me know!
- If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. Remember that you can also submit anonymous feedback (which will lead to me making a general announcement to the class, if necessary to address your concerns). If you prefer to speak with someone outside of the course, the Vice President for Student Affairs is an excellent resource. 
- I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).
