## Religious Observances 

CSU does not discriminate on the basis of religion. Reasonable accommodation should be made to allow individuals to observe their established religious holidays.

Please see [CSU's Religious Observances Calendar](https://calendar.colostate.edu/observances/).

Students seeking an exemption from attending class or completing assigned course work for a religious holiday will need to fill out the [Religious Accommodation Request Form](https://studentaffairs.colostate.edu/resources/resources-faculty-staff/administrative-information/religious-holidays/) and turn it in to the Division of Student Affairs, located on the second level of the Administration building.

Once turned in, the Division of Student Affairs will review the request and contact the student accordingly. If approved, the student will receive a memo from the Dean of Students to give to their professor or course instructor.

Students are asked to turn in the request forms as soon as the conflict is noticed. Similarly, unanticipated conflicts requiring a religious observance, such as a death in the family, can also be reviewed.
