### Universal Design for Learning/Accommodation of Needs

I am committed to the principle of universal learning. This means that our classroom, our virtual spaces, our practices, and our interactions be as inclusive as possible. Mutual respect, civility, and the ability to listen and observe others carefully are crucial to universal learning. 
If you are a student who will need accommodations in this class, please contact me to discuss your individual needs. Any accommodation must be discussed in a timely manner. A verifying memo from [The Student Disability Center](https://disabilitycenter.colostate.edu/) may be required before any accommodation is provided. I ask that students that require accommodations that are not met by the standard course set up to arrange a time to discuss the accommodation with me.  

The Student Disability Center (SDC) has the authority to verify and confirm the eligibility of students with disabilities for the majority of accommodations. While some accommodations may be provided by other departments, a student is not automatically eligible for those accommodations unless their disability can be verified and the need for the accommodation confirmed, either through SDC or through acceptable means defined by the particular department. Faculty and staff may consult with the SDC staff whenever there is doubt as to the appropriateness of an accommodative request by a student with a disability.  

The goal of SDC is to normalize disability as part of the culture of diversity at Colorado State University. The characteristic of having a disability simply provides the basis of the support that is available to students. The goal is to ensure students with disabilities have the opportunity to be as successful as they have the capability to be.  

Support and services are offered to student with functional limitations due to visual, hearing, learning, or mobility disabilities as well as to students who have specific physical or mental health conditions due to epilepsy, diabetes, asthma, AIDS, psychiatric diagnoses, etc. Students who are temporarily disabled are also eligible for support and assistance.  

Any student who is enrolled at CSU, and who self-identifies with SDC as having a disability, is eligible for support from SDC. Specific accommodations are determined individually for each student and must be supported by appropriate documentation and/or evaluation of needs consistent with a particular type of disability. SDC reserves the right to ask for any appropriate documentation of disability in order to determine a student's eligibility for accommodations as well as in support for specific accommodative requests. The accommodative process begins once a student meets with an accommodation’s specialist in the SDC.

If the student requires an accommodation for in-person exams/quizzes, they must arrange for the accommodation by the SDC Accessible Testing Center. 
